services:  
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: ["gpu"]
            count: all
    environment:
      - OLLAMA_DEBUG=1
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: always
    networks:
      - app-network

  open-webui:
    #build:
    #  context: .
    #  args:
    #    OLLAMA_BASE_URL: '/ollama'
    #  dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
    ollama:
      driver: local
    open-webui: 
      driver: local

#docker compose exec ollama ollama run llama3:8b-instruct-q8_0