services:  
  ollama:
    container_name: ollama
    image: ollama/ollama:0.2.5
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: ["gpu"]
            count: all
    environment:
      - OLLAMA_DEBUG=1
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: always

volumes:
    ollama:

#docker compose exec ollama ollama run llama3:8b-instruct-q8_0